version: '2'

services:
  mednuvem-server:
    image: espdlucas/mednuvem-server:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "5000:5000"
    environment:
      - REMOTE_DEBUGGING
